os: linux
dist: focal

# we install anaconda, so no need to use python
language: generic

# install poppler
addons:
  apt:
    packages:
      - poppler-utils
      - fonts-firacode


install:
  # first anaconda, we install miniconda and then the conda
  # package as there is now version independent link for anaconda
  - curl -sSLo miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash ./miniconda.sh -p $HOME/conda -b
  - source $HOME/conda/etc/profile.d/conda.sh
  - conda activate
  - conda install --yes matplotlib numpy pandas requests scipy sympy
  - pip install uncertainties jupyter_contrib_nbextensions https://github.com/maxnoe/texlive-batch-installation/archive/v0.2.1.tar.gz

  # install texlive minimal with what we need
  - |
    python -m install_texlive -p $HOME/texlive -t 2021 --collections='-acfghuDFG' \
    -i 'koma-script,babel,babel-french,csquotes,placeins,enumitem,biber,biblatex,siunitx,beamer,xpatch,blindtext,standalone,circuitikz,tikz-feynman,xstring,fontawesome5,mleftright,mhchem,tabulary,tabu,varwidth,lstaddons,tcolorbox,mwe,fira,firamath,firamath-otf,xits,threeparttable,environ,trimspaces,pgfopts,ncctools'
  # we need graphs from this document
  - export PATH=$HOME/texlive/2020/bin/x86_64-linux:$PATH
  - tlmgr install --with-doc tex-overview

script:
  - make

after_script:
  # grep for LaTeX errors to see what went wrong
  # ! inverts return code, so we fail if we find something
  - ! grep -R --include='*.log' '^!' -A 5 -B 5
